
const videolist=[{
        title:"Talking Tech and AI with Google CEO Sundar Pichai!", 
        img:"https://img.youtube.com/vi/n2RNcPRtAiY/mqdefault.jpg", 
        profile:"https://yt3.ggpht.com/ytc/AAUvwngW9TQgw7E7NqS3Qzd3Up3tjUzkpvMXPWAhYf3LaQ=s48-c-k-c0x00ffffff-no-rj", 
        timestamp:"May 22, 2021", 
        views:"1,264,163 views", 
        channelname:"Marques Brownlee"
    },
    {
        title:"The Understated Wisdom Of Sushant Singh Rajput",
        img:"https://img.youtube.com/vi/tcz07ZnWIDM/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngGXFu-5QDuWODD45MRfos-ck7SSnkT9sysTlsb=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Jun 16, 2020",
        views:"5,476,993 views",
        channelname:"Brut India"
    },
    {
        title:"Tanmay Bhat Reacts To Engineering Life ft. Prashasti, Vipul & Biswapati | Alma Matters",
        img:"https://img.youtube.com/vi/xYTmzBYvWGY/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwnh53ZRIGnyzC28QrfuggCINb3cfNbNWo4Uc6qR9=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"May 20, 2021",
        views:"792,010 views",
        channelname:"Netflix India",
    },
    {
        title:"🔴 Let's build SIGNAL with REACT NATIVE! (Navigation, Expo & Firebase)",
        img:"https://img.youtube.com/vi/MJzmZ9qmdaE/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngXcU2LcXQqcPyZFVwF_sV2zjB04K5RVFGE7heEwc4=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 4 months ago",
        views:"111,906 views",
        channelname:"Sonny Sangha",
    },
    {
        title:"🔴 Build a TWITTER Clone with REACT JS for Beginners",
        img:"https://img.youtube.com/vi/rJjaqSTzOxI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwniwccxGvXvGzzwka5f73aPbmdxvEX4G_cUd7TEzkw=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 9 months ago",
        views:"129,076 views",
        channelname:"Clever Progammer",
    },
    {
        title:"Sam Tsui - There For You (Official Music Video) | Sam Tsui",
        img:"https://img.youtube.com/vi/ABxucMf6ssw/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngxlVilVC5CuAbTfRY93IgaN6kvGSEo1JOtFbC1=s48-c-k-c0x00ffffff-no-rj-mo",
        timestamp:"Jan 19, 2019",
        views:"136,578 views",
        channelname:"TheSamTsui",
    },
    {
        title:"Steve Smith Makes 144 On Test Return | The Ashes Day 1 Highlights",
        img:"https://img.youtube.com/vi/K7JlaKMRccI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwnhHWy6peVIYHfnmgauOvWOe-dj8jp3XaA3NFjlVmQ=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Aug 2, 2019",
        views:"8,850,120 views",
        channelname:"England & Wales Cricket Board",
    },
    {
        title:"The Understated Wisdom Of Sushant Singh Rajput",
        img:"https://img.youtube.com/vi/tcz07ZnWIDM/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngGXFu-5QDuWODD45MRfos-ck7SSnkT9sysTlsb=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Jun 16, 2020",
        views:"5,476,993 views",
        channelname:"Brut India"
    },
    {
        title:"🔴 Build a TWITTER Clone with REACT JS for Beginners",
        img:"https://img.youtube.com/vi/rJjaqSTzOxI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwniwccxGvXvGzzwka5f73aPbmdxvEX4G_cUd7TEzkw=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 9 months ago",
        views:"129,076 views",
        channelname:"Clever Progammer",
    },
    {
        title:"Talking Tech and AI with Google CEO Sundar Pichai!", 
        img:"https://img.youtube.com/vi/n2RNcPRtAiY/mqdefault.jpg", 
        profile:"https://yt3.ggpht.com/ytc/AAUvwngW9TQgw7E7NqS3Qzd3Up3tjUzkpvMXPWAhYf3LaQ=s48-c-k-c0x00ffffff-no-rj", 
        timestamp:"May 22, 2021", 
        views:"1,264,163 views", 
        channelname:"Marques Brownlee"
    },
    {
        title:"Sam Tsui - There For You (Official Music Video) | Sam Tsui",
        img:"https://img.youtube.com/vi/ABxucMf6ssw/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngxlVilVC5CuAbTfRY93IgaN6kvGSEo1JOtFbC1=s48-c-k-c0x00ffffff-no-rj-mo",
        timestamp:"Jan 19, 2019",
        views:"136,578 views",
        channelname:"TheSamTsui",
    },
    {
        title:"The Understated Wisdom Of Sushant Singh Rajput",
        img:"https://img.youtube.com/vi/tcz07ZnWIDM/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngGXFu-5QDuWODD45MRfos-ck7SSnkT9sysTlsb=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Jun 16, 2020",
        views:"5,476,993 views",
        channelname:"Brut India"
    },
    {
        title:"Tanmay Bhat Reacts To Engineering Life ft. Prashasti, Vipul & Biswapati | Alma Matters",
        img:"https://img.youtube.com/vi/xYTmzBYvWGY/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwnh53ZRIGnyzC28QrfuggCINb3cfNbNWo4Uc6qR9=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"May 20, 2021",
        views:"792,010 views",
        channelname:"Netflix India",
    },
    {
        title:"🔴 Let's build SIGNAL with REACT NATIVE! (Navigation, Expo & Firebase)",
        img:"https://img.youtube.com/vi/MJzmZ9qmdaE/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngXcU2LcXQqcPyZFVwF_sV2zjB04K5RVFGE7heEwc4=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 4 months ago",
        views:"111,906 views",
        channelname:"Sonny Sangha",
    },
    {
        title:"🔴 Build a TWITTER Clone with REACT JS for Beginners",
        img:"https://img.youtube.com/vi/rJjaqSTzOxI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwniwccxGvXvGzzwka5f73aPbmdxvEX4G_cUd7TEzkw=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 9 months ago",
        views:"129,076 views",
        channelname:"Clever Progammer",
    },
    {
        title:"Sam Tsui - There For You (Official Music Video) | Sam Tsui",
        img:"https://img.youtube.com/vi/ABxucMf6ssw/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngxlVilVC5CuAbTfRY93IgaN6kvGSEo1JOtFbC1=s48-c-k-c0x00ffffff-no-rj-mo",
        timestamp:"Jan 19, 2019",
        views:"136,578 views",
        channelname:"TheSamTsui",
    },
    {
        title:"Steve Smith Makes 144 On Test Return | The Ashes Day 1 Highlights ",
        img:"https://img.youtube.com/vi/K7JlaKMRccI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwnhHWy6peVIYHfnmgauOvWOe-dj8jp3XaA3NFjlVmQ=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Aug 2, 2019",
        views:"8,850,120 views",
        channelname:"England & Wales Cricket Board",
    },
    {
        title:"The Understated Wisdom Of Sushant Singh Rajput",
        img:"https://img.youtube.com/vi/tcz07ZnWIDM/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngGXFu-5QDuWODD45MRfos-ck7SSnkT9sysTlsb=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Jun 16, 2020",
        views:"5,476,993 views",
        channelname:"Brut India"
    },
    {
        title:"🔴 Build a TWITTER Clone with REACT JS for Beginners",
        img:"https://img.youtube.com/vi/rJjaqSTzOxI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwniwccxGvXvGzzwka5f73aPbmdxvEX4G_cUd7TEzkw=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 9 months ago",
        views:"129,076 views",
        channelname:"Clever Progammer",
    },
    {
        title:"Talking Tech and AI with Google CEO Sundar Pichai!", 
        img:"https://img.youtube.com/vi/n2RNcPRtAiY/mqdefault.jpg", 
        profile:"https://yt3.ggpht.com/ytc/AAUvwngW9TQgw7E7NqS3Qzd3Up3tjUzkpvMXPWAhYf3LaQ=s48-c-k-c0x00ffffff-no-rj", 
        timestamp:"May 22, 2021", 
        views:"1,264,163 views", 
        channelname:"Marques Brownlee"
    },
    {
        title:"Sam Tsui - There For You (Official Music Video) | Sam Tsui",
        img:"https://img.youtube.com/vi/ABxucMf6ssw/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngxlVilVC5CuAbTfRY93IgaN6kvGSEo1JOtFbC1=s48-c-k-c0x00ffffff-no-rj-mo",
        timestamp:"Jan 19, 2019",
        views:"136,578 views",
        channelname:"TheSamTsui",
    },
    {
        title:"The Understated Wisdom Of Sushant Singh Rajput",
        img:"https://img.youtube.com/vi/tcz07ZnWIDM/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngGXFu-5QDuWODD45MRfos-ck7SSnkT9sysTlsb=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Jun 16, 2020",
        views:"5,476,993 views",
        channelname:"Brut India"
    },
    {
        title:"Tanmay Bhat Reacts To Engineering Life ft. Prashasti, Vipul & Biswapati | Alma Matters",
        img:"https://img.youtube.com/vi/xYTmzBYvWGY/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwnh53ZRIGnyzC28QrfuggCINb3cfNbNWo4Uc6qR9=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"May 20, 2021",
        views:"792,010 views",
        channelname:"Netflix India",
    },
    {
        title:"🔴 Let's build SIGNAL with REACT NATIVE! (Navigation, Expo & Firebase)",
        img:"https://img.youtube.com/vi/MJzmZ9qmdaE/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwngXcU2LcXQqcPyZFVwF_sV2zjB04K5RVFGE7heEwc4=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 4 months ago",
        views:"111,906 views",
        channelname:"Sonny Sangha",
    },
    {
        title:"🔴 Build a TWITTER Clone with REACT JS for Beginners",
        img:"https://img.youtube.com/vi/rJjaqSTzOxI/mqdefault.jpg",
        profile:"https://yt3.ggpht.com/ytc/AAUvwniwccxGvXvGzzwka5f73aPbmdxvEX4G_cUd7TEzkw=s48-c-k-c0x00ffffff-no-rj",
        timestamp:"Streamed 9 months ago",
        views:"129,076 views",
        channelname:"Clever Progammer",
    },


]

export default videolist;